type Admin {
  _id: ID!
  name: String!
  email: String!
  password: String!
}

type Project {
  _id: ID!
  title: String!
  dateAdded: String!
  githubLink: String
  demoLink: String
  imageUrl: String
  tags: [String]!
}

type Token {
  token: String!
}

type Mutation {
  signinAdmin(email: String!, password: String!): Token
  signupAdmin(name: String!, password: String!, email: String!): Token
  postProject(
    title: String!
    githubLink: String
    demoLink: String
    imageUrl: String
    tags: [String!]!
  ): Project!
}

type Query {
  sayHi: Token
}
